// <auto-generated />
using System;
using ChefKnifeStudios.TransitJazz.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChefKnifeStudios.TransitJazz.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001204629_CreateCityCategoryStatistics")]
    partial class CreateCityCategoryStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChefKnifeStudios.TransitJazz.Server.Data.Models.CityCategoryHourStatistic", b =>
                {
                    b.Property<string>("CitySlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city_slug");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("HourStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_start_utc");

                    b.Property<long>("ActiveVehicleCountSum")
                        .HasColumnType("bigint")
                        .HasColumnName("active_vehicle_count_sum");

                    b.Property<string>("CollectionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("collection_status");

                    b.Property<int>("CoveredMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("covered_minutes");

                    b.Property<long>("CrossingsPublishedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_published_count");

                    b.Property<string>("DefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("definition_version");

                    b.Property<long>("DistanceIntervalCount")
                        .HasColumnType("bigint")
                        .HasColumnName("distance_interval_count");

                    b.Property<decimal>("DistanceMetersSum")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("distance_meters_sum");

                    b.Property<long>("DistanceRejectedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("distance_rejected_count");

                    b.Property<long?>("DistinctActiveVehicleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("distinct_active_vehicle_count");

                    b.Property<long>("FailedCycleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("failed_cycle_count");

                    b.Property<DateTime?>("FirstCycleUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_cycle_utc");

                    b.Property<bool>("HasConflict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_conflict");

                    b.Property<int>("HealthyCadenceLimitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("healthy_cadence_limit_seconds");

                    b.Property<DateTime?>("LastCycleUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_cycle_utc");

                    b.Property<decimal?>("MaxObservationGapSeconds")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("max_observation_gap_seconds");

                    b.Property<long>("ObservedCycleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_cycle_count");

                    b.Property<long>("ValidActiveSampleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("valid_active_sample_count");

                    b.Property<long>("ValidPublishCycleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("valid_publish_cycle_count");

                    b.HasKey("CitySlug", "Category", "HourStartUtc");

                    b.ToTable("city_category_hour_statistics", null, t =>
                        {
                            t.HasCheckConstraint("ck_city_category_hour_aligned", "date_trunc('hour', hour_start_utc AT TIME ZONE 'UTC') = hour_start_utc AT TIME ZONE 'UTC'");

                            t.HasCheckConstraint("ck_city_category_hour_complete", "collection_status <> 'Complete' OR (covered_minutes = 60 AND distinct_active_vehicle_count IS NOT NULL AND observed_cycle_count > 0 AND valid_active_sample_count = observed_cycle_count AND valid_publish_cycle_count = observed_cycle_count AND failed_cycle_count = 0 AND max_observation_gap_seconds IS NOT NULL AND max_observation_gap_seconds <= healthy_cadence_limit_seconds)");

                            t.HasCheckConstraint("ck_city_category_hour_no_data", "collection_status <> 'NoData' OR (valid_active_sample_count = 0 AND valid_publish_cycle_count = 0 AND active_vehicle_count_sum = 0 AND distance_meters_sum = 0 AND distance_interval_count = 0 AND crossings_published_count = 0)");

                            t.HasCheckConstraint("ck_city_category_hour_nonnegative", "healthy_cadence_limit_seconds BETWEEN 1 AND 60 AND observed_cycle_count >= 0 AND valid_active_sample_count >= 0 AND valid_publish_cycle_count >= 0 AND failed_cycle_count >= 0 AND active_vehicle_count_sum >= 0 AND distance_meters_sum >= 0 AND distance_interval_count >= 0 AND distance_rejected_count >= 0 AND crossings_published_count >= 0 AND (distinct_active_vehicle_count IS NULL OR distinct_active_vehicle_count >= 0) AND covered_minutes BETWEEN 0 AND 60 AND (max_observation_gap_seconds IS NULL OR max_observation_gap_seconds >= 0)");

                            t.HasCheckConstraint("ck_city_category_hour_samples", "valid_active_sample_count <= observed_cycle_count AND valid_publish_cycle_count <= observed_cycle_count AND failed_cycle_count <= observed_cycle_count");

                            t.HasCheckConstraint("ck_city_category_hour_status", "collection_status IN ('Complete','Partial','NoData')");
                        });
                });

            modelBuilder.Entity("ChefKnifeStudios.TransitJazz.Server.Data.Models.CityCategoryMinuteStatistic", b =>
                {
                    b.Property<string>("CitySlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city_slug");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("StatMinuteUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stat_minute_utc");

                    b.Property<long>("ActiveVehicleCountSum")
                        .HasColumnType("bigint")
                        .HasColumnName("active_vehicle_count_sum");

                    b.Property<string>("CollectionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("collection_status");

                    b.Property<long>("CrossingsPublishedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_published_count");

                    b.Property<string>("DefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("definition_version");

                    b.Property<long>("DistanceIntervalCount")
                        .HasColumnType("bigint")
                        .HasColumnName("distance_interval_count");

                    b.Property<decimal>("DistanceMetersSum")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("distance_meters_sum");

                    b.Property<long>("DistanceRejectedCount")
                        .HasColumnType("bigint")
                        .HasColumnName("distance_rejected_count");

                    b.Property<long>("FailedCycleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("failed_cycle_count");

                    b.Property<DateTime?>("FirstCycleUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_cycle_utc");

                    b.Property<bool>("HasConflict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_conflict");

                    b.Property<int>("HealthyCadenceLimitSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("healthy_cadence_limit_seconds");

                    b.Property<DateTime?>("LastCycleUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_cycle_utc");

                    b.Property<decimal?>("MaxObservationGapSeconds")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("max_observation_gap_seconds");

                    b.Property<long>("ObservedCycleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("observed_cycle_count");

                    b.Property<long>("ValidActiveSampleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("valid_active_sample_count");

                    b.Property<long>("ValidPublishCycleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("valid_publish_cycle_count");

                    b.HasKey("CitySlug", "Category", "StatMinuteUtc");

                    b.ToTable("city_category_minute_statistics", null, t =>
                        {
                            t.HasCheckConstraint("ck_city_category_minute_aligned", "date_trunc('minute', stat_minute_utc AT TIME ZONE 'UTC') = stat_minute_utc AT TIME ZONE 'UTC'");

                            t.HasCheckConstraint("ck_city_category_minute_complete", "collection_status <> 'Complete' OR (observed_cycle_count > 0 AND valid_active_sample_count = observed_cycle_count AND valid_publish_cycle_count = observed_cycle_count AND failed_cycle_count = 0 AND max_observation_gap_seconds IS NOT NULL AND max_observation_gap_seconds <= healthy_cadence_limit_seconds)");

                            t.HasCheckConstraint("ck_city_category_minute_no_data", "collection_status <> 'NoData' OR (valid_active_sample_count = 0 AND valid_publish_cycle_count = 0 AND active_vehicle_count_sum = 0 AND distance_meters_sum = 0 AND distance_interval_count = 0 AND crossings_published_count = 0)");

                            t.HasCheckConstraint("ck_city_category_minute_nonnegative", "healthy_cadence_limit_seconds BETWEEN 1 AND 60 AND observed_cycle_count >= 0 AND valid_active_sample_count >= 0 AND valid_publish_cycle_count >= 0 AND failed_cycle_count >= 0 AND active_vehicle_count_sum >= 0 AND distance_meters_sum >= 0 AND distance_interval_count >= 0 AND distance_rejected_count >= 0 AND crossings_published_count >= 0 AND (max_observation_gap_seconds IS NULL OR max_observation_gap_seconds >= 0)");

                            t.HasCheckConstraint("ck_city_category_minute_samples", "valid_active_sample_count <= observed_cycle_count AND valid_publish_cycle_count <= observed_cycle_count AND failed_cycle_count <= observed_cycle_count");

                            t.HasCheckConstraint("ck_city_category_minute_status", "collection_status IN ('Complete','Partial','NoData')");
                        });
                });

            modelBuilder.Entity("ChefKnifeStudios.TransitJazz.Server.Data.Models.CityMinuteStatistic", b =>
                {
                    b.Property<string>("CitySlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city_slug");

                    b.Property<DateTime>("StatMinuteUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stat_minute_utc");

                    b.Property<long?>("BatchWireBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_wire_bytes");

                    b.Property<string>("CollectionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("collection_status");

                    b.Property<long?>("CrossingBaselineCache")
                        .HasColumnType("bigint")
                        .HasColumnName("crossing_baseline_cache");

                    b.Property<long?>("CrossingsSuppressedDeltaLeqZero")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_delta_leq_zero");

                    b.Property<long?>("CrossingsSuppressedFirstSeen")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_first_seen");

                    b.Property<long?>("CrossingsSuppressedTeleport")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_teleport");

                    b.Property<long?>("CrossingsSuppressedTransfer")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_transfer");

                    b.Property<decimal?>("CycleDurationP95Seconds")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("cycle_duration_p95_seconds");

                    b.Property<decimal?>("CycleErrorRatePerSecond")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("cycle_error_rate_per_second");

                    b.Property<decimal?>("CycleRatePerSecond")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("cycle_rate_per_second");

                    b.Property<bool?>("HasInputRecords")
                        .HasColumnType("boolean")
                        .HasColumnName("has_input_records");

                    b.Property<bool?>("Healthy")
                        .HasColumnType("boolean")
                        .HasColumnName("healthy");

                    b.Property<bool?>("InputFetchOk")
                        .HasColumnType("boolean")
                        .HasColumnName("input_fetch_ok");

                    b.Property<decimal?>("InputLagSeconds")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("input_lag_seconds");

                    b.Property<long?>("InputRecordsValid")
                        .HasColumnType("bigint")
                        .HasColumnName("input_records_valid");

                    b.Property<long?>("InputSourceFailures")
                        .HasColumnType("bigint")
                        .HasColumnName("input_source_failures");

                    b.Property<bool?>("InputTimestampKnown")
                        .HasColumnType("boolean")
                        .HasColumnName("input_timestamp_known");

                    b.Property<long?>("LastCycledUnixSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("last_cycled_unix_seconds");

                    b.Property<long?>("LastWorkedUnixSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("last_worked_unix_seconds");

                    b.Property<long?>("RouteIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("route_index");

                    b.Property<long?>("RouteTriggerPointCache")
                        .HasColumnType("bigint")
                        .HasColumnName("route_trigger_point_cache");

                    b.Property<string>("SourceDefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_definition_version");

                    b.Property<long?>("TonesEmitted")
                        .HasColumnType("bigint")
                        .HasColumnName("tones_emitted");

                    b.Property<long?>("VehicleStateCache")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_state_cache");

                    b.Property<long?>("VehiclesProcessed")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicles_processed");

                    b.HasKey("CitySlug", "StatMinuteUtc");

                    b.ToTable("city_minute_statistics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
