// <auto-generated />
using System;
using ChefKnifeStudios.TransitJazz.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChefKnifeStudios.TransitJazz.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920201730_CreateCityMinuteStatistics")]
    partial class CreateCityMinuteStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChefKnifeStudios.TransitJazz.Server.Data.Models.CityMinuteStatistic", b =>
                {
                    b.Property<string>("CitySlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city_slug");

                    b.Property<DateTime>("StatMinuteUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stat_minute_utc");

                    b.Property<long?>("BatchWireBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_wire_bytes");

                    b.Property<string>("CollectionStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("collection_status");

                    b.Property<long?>("CrossingBaselineCache")
                        .HasColumnType("bigint")
                        .HasColumnName("crossing_baseline_cache");

                    b.Property<long?>("CrossingsSuppressedDeltaLeqZero")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_delta_leq_zero");

                    b.Property<long?>("CrossingsSuppressedFirstSeen")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_first_seen");

                    b.Property<long?>("CrossingsSuppressedTeleport")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_teleport");

                    b.Property<long?>("CrossingsSuppressedTransfer")
                        .HasColumnType("bigint")
                        .HasColumnName("crossings_suppressed_transfer");

                    b.Property<decimal?>("CycleDurationP95Seconds")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("cycle_duration_p95_seconds");

                    b.Property<decimal?>("CycleErrorRatePerSecond")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("cycle_error_rate_per_second");

                    b.Property<decimal?>("CycleRatePerSecond")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("cycle_rate_per_second");

                    b.Property<bool?>("HasInputRecords")
                        .HasColumnType("boolean")
                        .HasColumnName("has_input_records");

                    b.Property<bool?>("Healthy")
                        .HasColumnType("boolean")
                        .HasColumnName("healthy");

                    b.Property<bool?>("InputFetchOk")
                        .HasColumnType("boolean")
                        .HasColumnName("input_fetch_ok");

                    b.Property<decimal?>("InputLagSeconds")
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("input_lag_seconds");

                    b.Property<long?>("InputRecordsValid")
                        .HasColumnType("bigint")
                        .HasColumnName("input_records_valid");

                    b.Property<long?>("InputSourceFailures")
                        .HasColumnType("bigint")
                        .HasColumnName("input_source_failures");

                    b.Property<bool?>("InputTimestampKnown")
                        .HasColumnType("boolean")
                        .HasColumnName("input_timestamp_known");

                    b.Property<long?>("LastCycledUnixSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("last_cycled_unix_seconds");

                    b.Property<long?>("LastWorkedUnixSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("last_worked_unix_seconds");

                    b.Property<long?>("RouteIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("route_index");

                    b.Property<long?>("RouteTriggerPointCache")
                        .HasColumnType("bigint")
                        .HasColumnName("route_trigger_point_cache");

                    b.Property<string>("SourceDefinitionVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_definition_version");

                    b.Property<long?>("TonesEmitted")
                        .HasColumnType("bigint")
                        .HasColumnName("tones_emitted");

                    b.Property<long?>("VehicleStateCache")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicle_state_cache");

                    b.Property<long?>("VehiclesProcessed")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicles_processed");

                    b.HasKey("CitySlug", "StatMinuteUtc");

                    b.ToTable("city_minute_statistics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
