<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ChefKnifeStudios.TransitJazz.Server.WebAPI.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.41" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ChefKnifeStudios.TransitJazz.Shared\ChefKnifeStudios.TransitJazz.Shared.csproj" />
    <ProjectReference Include="..\ChefKnifeStudios.TransitJazz.Server.TransitDataWorker\ChefKnifeStudios.TransitJazz.Server.TransitDataWorker.csproj" />
  </ItemGroup>
</Project>
