<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ChefKnifeStudios.MartaJazz.Client.WebApp</RootNamespace>
    <SupportedPlatform>browser</SupportedPlatform>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChefKnifeStudios.MartaJazz.Client.Shared\ChefKnifeStudios.MartaJazz.Client.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\favicon\" />
  </ItemGroup>
</Project>
